<?php

namespace Godart\ChassisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChassisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChassisRepository extends EntityRepository
{
}
