parameters:
#    godart_ddprix.example.class: Godart\DdprixBundle\Example

services:
#    godart_ddprix.example:
#        class: %godart_ddprix.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
