parameters:
#    godart_chassis.example.class: Godart\ChassisBundle\Example

services:
#    godart_chassis.example:
#        class: %godart_chassis.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
