<?php

namespace Godart\DdprixBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DdprixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DdprixRepository extends EntityRepository
{
}
